"""empty message

Revision ID: 0f521504c4c6
Revises: 7d4dd1c3bba9
Create Date: 2016-07-10 23:44:12.403098

"""

# revision identifiers, used by Alembic.
revision = '0f521504c4c6'
down_revision = '7d4dd1c3bba9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    ### end Alembic commands ###
