"""empty message

Revision ID: 1bd44724065c
Revises: e674779e9b04
Create Date: 2018-09-23 12:37:25.444971

"""

# revision identifiers, used by Alembic.
revision = '1bd44724065c'
down_revision = 'e674779e9b04'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('band_songs',
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['band.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], )
    )
    
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('setlist', 'song_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('setlist', 'show_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('band_songs')
    ### end Alembic commands ###
