"""empty message

Revision ID: 40a265850cb1
Revises: c192bcb1fde0
Create Date: 2016-07-23 01:05:22.603225

"""

# revision identifiers, used by Alembic.
revision = '40a265850cb1'
down_revision = 'c192bcb1fde0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show_song', sa.Column('order', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show_song', 'order')
    ### end Alembic commands ###
