"""empty message

Revision ID: 7d4dd1c3bba9
Revises: 42fa9a35c694
Create Date: 2016-07-06 20:17:01.891188

"""

# revision identifiers, used by Alembic.
revision = '7d4dd1c3bba9'
down_revision = '42fa9a35c694'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    ### end Alembic commands ###
