"""empty message

Revision ID: c192bcb1fde0
Revises: d8f2a6b37135
Create Date: 2016-07-21 14:09:11.797107

"""

# revision identifiers, used by Alembic.
revision = 'c192bcb1fde0'
down_revision = 'd8f2a6b37135'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('band_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=4000), nullable=True),
    sa.Column('contact', sa.String(length=4000), nullable=True),
    sa.Column('pay', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.String(length=4000), nullable=True),
    sa.ForeignKeyConstraint(['band_id'], ['band.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('show_song',
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_song')
    op.drop_table('show')
    ### end Alembic commands ###
