"""empty message

Revision ID: d8f2a6b37135
Revises: 16ab3e3771b4
Create Date: 2016-07-18 12:57:48.499231

"""

# revision identifiers, used by Alembic.
revision = 'd8f2a6b37135'
down_revision = '16ab3e3771b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('artist', sa.String(length=128), nullable=True),
    sa.Column('key', sa.String(length=8), nullable=True),
    sa.Column('tempo', sa.Integer(), nullable=True),
    sa.Column('duration', sa.String(length=5), nullable=True),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.Column('notes', sa.String(length=4000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    ### end Alembic commands ###
