"""empty message

Revision ID: e674779e9b04
Revises: 40a265850cb1
Create Date: 2016-07-24 23:27:14.912074

"""

# revision identifiers, used by Alembic.
revision = 'e674779e9b04'
down_revision = '40a265850cb1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setlist',
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('song_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], )
    )
    op.drop_table('show_song')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_song',
    sa.Column('show_id', sa.INTEGER(), nullable=True),
    sa.Column('song_id', sa.INTEGER(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.Column('position', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], )
    )
    op.drop_table('setlist')
    ### end Alembic commands ###
